// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-RuBlYxPQeLRffKFQ7cIvAgmP8bKiRA',
    appId: '1:869481983448:web:a245bc9a5d0653639e16ad',
    messagingSenderId: '869481983448',
    projectId: 'gobuy-ecom',
    authDomain: 'gobuy-ecom.firebaseapp.com',
    storageBucket: 'gobuy-ecom.firebasestorage.app',
    measurementId: 'G-4P9K3125T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMlFF3KxPw20MTOnciZHpCN56Z2ee_51w',
    appId: '1:869481983448:android:fec34de1615166a49e16ad',
    messagingSenderId: '869481983448',
    projectId: 'gobuy-ecom',
    storageBucket: 'gobuy-ecom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR18Fm0VQPyCGmuOyClPwVLO0ivga78cY',
    appId: '1:869481983448:ios:5dc365caef67156f9e16ad',
    messagingSenderId: '869481983448',
    projectId: 'gobuy-ecom',
    storageBucket: 'gobuy-ecom.firebasestorage.app',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR18Fm0VQPyCGmuOyClPwVLO0ivga78cY',
    appId: '1:869481983448:ios:5dc365caef67156f9e16ad',
    messagingSenderId: '869481983448',
    projectId: 'gobuy-ecom',
    storageBucket: 'gobuy-ecom.firebasestorage.app',
    iosBundleId: 'com.example.eComm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL-RuBlYxPQeLRffKFQ7cIvAgmP8bKiRA',
    appId: '1:869481983448:web:0b9cc763b4e7be4b9e16ad',
    messagingSenderId: '869481983448',
    projectId: 'gobuy-ecom',
    authDomain: 'gobuy-ecom.firebaseapp.com',
    storageBucket: 'gobuy-ecom.firebasestorage.app',
    measurementId: 'G-E095M23PRJ',
  );
}
